spring:
  profiles:
    active: dev

---
spring:
  profiles: dev # 开发环境
  application:
    name: my-cloud-demo-config-dev-v3
---
spring:
  profiles: test # 测试环境
  application:
    name: my-cloud-demo-config-test-v3