spring:
  profiles:
    active: dev

---
spring:
  profiles: dev #
  application:
    name: spring-cloud-demo-config-dev
---
spring:
  profiles: test #
  application:
    name: spring-cloud-demo-config-test